server {
    listen 80;
    server_name _;

    client_max_body_size 10G;

    location /api/ {
        proxy_pass http://server:8000/api/;
        proxy_read_timeout 1800s;
        proxy_send_timeout 1800s;
        proxy_request_buffering off;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}