# Generated by Django 5.2.15 on 2026-07-08 09:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dataset_is_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('receiving', 'Receiving'), ('ready_for_review', 'Ready for review'), ('creating_dataset', 'Creating dataset'), ('dataset_created', 'Dataset created'), ('pipeline_queued', 'Pipeline queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='receiving', max_length=40)),
                ('calling_ae_title', models.CharField(blank=True, max_length=64)),
                ('called_ae_title', models.CharField(blank=True, max_length=64)),
                ('patient_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('study_instance_uid', models.CharField(db_index=True, max_length=255)),
                ('series_instance_uid', models.CharField(db_index=True, max_length=255)),
                ('study_description', models.CharField(blank=True, max_length=255)),
                ('series_description', models.CharField(blank=True, max_length=255)),
                ('modality', models.CharField(blank=True, db_index=True, max_length=32)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('first_file_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_file_received_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicom_import_sessions', to='core.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_import_sessions', to=settings.AUTH_USER_MODEL)),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicom_import_sessions', to='core.pipelinerun')),
            ],
            options={
                'ordering': ['-last_file_received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DicomImportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sop_instance_uid', models.CharField(db_index=True, max_length=255)),
                ('relative_path', models.TextField()),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('instance_number', models.IntegerField(blank=True, null=True)),
                ('image_position_patient_z', models.FloatField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.dicomimportsession')),
            ],
            options={
                'ordering': ['instance_number', 'relative_path'],
            },
        ),
        migrations.AddConstraint(
            model_name='dicomimportsession',
            constraint=models.UniqueConstraint(fields=('owner', 'study_instance_uid', 'series_instance_uid'), name='uq_dicom_import_owner_study_series'),
        ),
        migrations.AddConstraint(
            model_name='dicomimportfile',
            constraint=models.UniqueConstraint(fields=('session', 'sop_instance_uid'), name='uq_dicom_import_file_session_sop'),
        ),
    ]
